name = "TrixiTest"
uuid = "0a316866-cbd0-4425-8bcb-08103b2c1f26"
authors = ["Joshua Lampert <joshua.lampert@uni-hamburg.de>"]
version = "0.2.1-DEV"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TrixiBase = "9a0f1c46-06d5-4909-a5a3-ce25d3fa3284"

[compat]
Test = "1"
TrixiBase = "0.1.6"
julia = "1.10"
